import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLanguage extends ChangeNotifier {
  static final AppLanguage _instance = AppLanguage._();
  factory AppLanguage() => _instance;
  AppLanguage._();

  String _lang = 'ms';
  String get lang => _lang;
  bool get isMalay => _lang == 'ms';

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('app_language') ?? 'ms';
  }

  Future<void> setLanguage(String lang) async {
    _lang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', lang);
    notifyListeners();
  }

  String get(String key) => (_translations[key]?[_lang]) ?? key;

  static final Map<String, Map<String, String>> _translations = {
    // ═══════════════════════════════════════
    // COMMON / SHARED
    // ═══════════════════════════════════════
    'batal': {'ms': 'BATAL', 'en': 'CANCEL'},
    'simpan': {'ms': 'SIMPAN', 'en': 'SAVE'},
    'padam': {'ms': 'PADAM', 'en': 'DELETE'},
    'tambah': {'ms': 'TAMBAH', 'en': 'ADD'},
    'kemaskini': {'ms': 'KEMASKINI', 'en': 'UPDATE'},
    'tutup': {'ms': 'TUTUP', 'en': 'CLOSE'},
    'ok': {'ms': 'OK', 'en': 'OK'},
    'ya': {'ms': 'YA', 'en': 'YES'},
    'tidak': {'ms': 'TIDAK', 'en': 'NO'},
    'cari': {'ms': 'CARI', 'en': 'SEARCH'},
    'selesai': {'ms': 'SELESAI', 'en': 'DONE'},
    'hantar_wa': {'ms': 'HANTAR WA', 'en': 'SEND WA'},
    'buka_print_pdf': {'ms': 'BUKA & PRINT PDF', 'en': 'OPEN & PRINT PDF'},
    'salin_link': {'ms': 'SALIN LINK', 'en': 'COPY LINK'},
    'cetak': {'ms': 'CETAK', 'en': 'PRINT'},
    'terbaru': {'ms': 'Terbaru', 'en': 'Latest'},
    'terlama': {'ms': 'Terlama', 'en': 'Oldest'},
    'tiada_padanan': {'ms': 'Tiada padanan', 'en': 'No match found'},
    'semua': {'ms': 'Semua', 'en': 'All'},
    'status': {'ms': 'Status', 'en': 'Status'},
    'tarikh': {'ms': 'Tarikh', 'en': 'Date'},
    'kembali': {'ms': 'Kembali', 'en': 'Back'},
    'menjana_pdf': {'ms': 'Menjana PDF...', 'en': 'Generating PDF...'},
    'scan_qr_barcode': {'ms': 'SCAN QR / BARCODE', 'en': 'SCAN QR / BARCODE'},
    'tiada_rekod': {'ms': 'Tiada rekod', 'en': 'No records'},
    'reverse': {'ms': 'REVERSE', 'en': 'REVERSE'},
    'pulihkan': {'ms': 'PULIHKAN', 'en': 'RESTORE'},
    'regular': {'ms': 'REGULAR', 'en': 'REGULAR'},
    'online': {'ms': 'ONLINE', 'en': 'ONLINE'},
    'offline': {'ms': 'OFFLINE', 'en': 'OFFLINE'},
    'view': {'ms': 'VIEW', 'en': 'VIEW'},
    'whatsapp': {'ms': 'WhatsApp', 'en': 'WhatsApp'},
    'salin': {'ms': 'Salin', 'en': 'Copy'},
    'link_disalin': {'ms': 'Link disalin!', 'en': 'Link copied!'},
    'ralat': {'ms': 'Ralat', 'en': 'Error'},
    'staf': {'ms': 'STAF', 'en': 'STAFF'},

    // ═══════════════════════════════════════
    // SETTINGS SCREEN
    // ═══════════════════════════════════════
    'settings_maklumat_cawangan': {'ms': 'MAKLUMAT CAWANGAN', 'en': 'BRANCH INFO'},
    'settings_tukar_logo': {'ms': 'TUKAR LOGO', 'en': 'CHANGE LOGO'},
    'settings_upload_logo': {'ms': 'UPLOAD LOGO (Max 200KB)', 'en': 'UPLOAD LOGO (Max 200KB)'},
    'settings_nama_kedai': {'ms': 'Nama Kedai', 'en': 'Shop Name'},
    'settings_no_ssm': {'ms': 'No SSM', 'en': 'SSM No'},
    'settings_alamat': {'ms': 'Alamat', 'en': 'Address'},
    'settings_no_telefon': {'ms': 'No Telefon', 'en': 'Phone No'},
    'settings_emel': {'ms': 'Emel', 'en': 'Email'},
    'settings_shop_id': {'ms': 'Shop ID', 'en': 'Shop ID'},
    'settings_tetapan_printer': {'ms': 'TETAPAN PRINTER', 'en': 'PRINTER SETTINGS'},
    'settings_tiada_printer': {'ms': 'Tiada printer — tekan TAMBAH untuk setup', 'en': 'No printer — press ADD to setup'},
    'settings_pilih_jenis_printer': {'ms': 'PILIH JENIS PRINTER', 'en': 'SELECT PRINTER TYPE'},
    'settings_printer_80mm': {'ms': 'PRINTER 80MM', 'en': '80MM PRINTER'},
    'settings_resit_thermal_bt': {'ms': 'Resit thermal — Bluetooth', 'en': 'Thermal receipt — Bluetooth'},
    'settings_printer_a4a5': {'ms': 'PRINTER A4/A5', 'en': 'A4/A5 PRINTER'},
    'settings_printer_biasa_wifi': {'ms': 'Printer biasa — WiFi', 'en': 'Normal printer — WiFi'},
    'settings_printer_label': {'ms': 'PRINTER LABEL', 'en': 'LABEL PRINTER'},
    'settings_label_sticker_bt': {'ms': 'Label sticker — Bluetooth', 'en': 'Label sticker — Bluetooth'},
    'settings_tetapan_borang': {'ms': 'TETAPAN BORANG & RESIT', 'en': 'FORM & RECEIPT SETTINGS'},
    'settings_bil_staff': {'ms': 'Bilangan Pilihan Staff (Borang)', 'en': 'Staff Selection Count (Form)'},
    'settings_1_kotak': {'ms': '1 Kotak (In-Charge)', 'en': '1 Box (In-Charge)'},
    'settings_2_kotak': {'ms': '2 Kotak (Terima & Baiki)', 'en': '2 Boxes (Receive & Repair)'},
    'settings_3_kotak': {'ms': '3 Kotak (Terima, Baiki & Serah)', 'en': '3 Boxes (Receive, Repair & Deliver)'},
    'settings_template_dokumen': {'ms': 'TEMPLATE DOKUMEN', 'en': 'DOCUMENT TEMPLATE'},
    'settings_nota_invoice': {'ms': 'NOTA INVOICE / QUOTATION / CLAIM / BOOKING', 'en': 'INVOICE / QUOTATION / CLAIM / BOOKING NOTES'},
    'settings_keselamatan_admin': {'ms': 'KESELAMATAN ADMIN', 'en': 'ADMIN SECURITY'},
    'settings_no_tel_admin': {'ms': 'No Telefon Admin (ID Login)', 'en': 'Admin Phone No (Login ID)'},
    'settings_kata_laluan_admin': {'ms': 'Kata Laluan Admin', 'en': 'Admin Password'},
    'settings_admin_dikunci': {'ms': 'Admin Telah Dikunci', 'en': 'Admin Locked'},
    'settings_simpan_kunci': {'ms': 'SIMPAN & KUNCI', 'en': 'SAVE & LOCK'},
    'settings_lupa': {'ms': 'LUPA', 'en': 'FORGOT'},
    'settings_warna_header': {'ms': 'WARNA HEADER', 'en': 'HEADER COLOR'},
    'settings_pilih_warna': {'ms': 'PILIH WARNA HEADER', 'en': 'SELECT HEADER COLOR'},
    'settings_bahasa': {'ms': 'BAHASA / LANGUAGE', 'en': 'LANGUAGE / BAHASA'},
    'settings_tetapan_disimpan': {'ms': 'Tetapan berjaya disimpan', 'en': 'Settings saved successfully'},
    'settings_pilihan_template': {'ms': 'PILIHAN TEMPLATE', 'en': 'TEMPLATE SELECTION'},
    'settings_pilih_template_desc': {'ms': 'Pilih template dan tekan preview untuk lihat hasilnya.', 'en': 'Select template and press preview to see the result.'},
    'settings_preview': {'ms': 'PREVIEW', 'en': 'PREVIEW'},
    'settings_tetapan_nota': {'ms': 'TETAPAN NOTA', 'en': 'NOTES SETTINGS'},
    'settings_kemaskini_nota_desc': {'ms': 'Kemaskini nota untuk invoice, quotation, claim & booking.', 'en': 'Update notes for invoice, quotation, claim & booking.'},
    'settings_lupa_kata_laluan': {'ms': 'Lupa Kata Laluan', 'en': 'Forgot Password'},
    'settings_lupa_desc': {'ms': 'Masukkan emel akaun anda untuk reset kata laluan.', 'en': 'Enter your account email to reset password.'},
    'settings_sahkan': {'ms': 'SAHKAN', 'en': 'CONFIRM'},
    'settings_menjana_preview': {'ms': 'Menjana Preview PDF...', 'en': 'Generating PDF Preview...'},
    'settings_preview_berjaya': {'ms': 'PDF preview berjaya dimuat turun. Data contoh sahaja — bukan resit sebenar.', 'en': 'PDF preview downloaded successfully. Sample data only — not an actual receipt.'},
    'settings_buka_pdf': {'ms': 'BUKA PDF', 'en': 'OPEN PDF'},
    'settings_printer_bt_80mm': {'ms': 'PRINTER BLUETOOTH (80mm)', 'en': 'BLUETOOTH PRINTER (80mm)'},
    'settings_scan_bt': {'ms': 'SCAN BLUETOOTH DEVICES', 'en': 'SCAN BLUETOOTH DEVICES'},
    'settings_peranti_dijumpai': {'ms': 'PERANTI DIJUMPAI', 'en': 'DEVICES FOUND'},
    'settings_printer_aktif': {'ms': 'PRINTER AKTIF', 'en': 'ACTIVE PRINTER'},
    'settings_simpan_manual': {'ms': 'SIMPAN MANUAL', 'en': 'SAVE MANUALLY'},
    'settings_taip_nama_manual': {'ms': 'Atau taip nama manual', 'en': 'Or type name manually'},
    'settings_printer_a4a5_wifi': {'ms': 'PRINTER A4/A5 (WiFi)', 'en': 'A4/A5 PRINTER (WiFi)'},
    'settings_memeriksa_ip': {'ms': 'Memeriksa 254 alamat IP dalam rangkaian anda...', 'en': 'Checking 254 IP addresses in your network...'},
    'settings_masuk_ip_manual': {'ms': 'Atau masukkan IP manual', 'en': 'Or enter IP manually'},
    'settings_single_staff_mode': {'ms': 'Single Staff Mode', 'en': 'Single Staff Mode'},
    'settings_preview_berjaya_dijana': {'ms': 'Preview berjaya dijana!', 'en': 'Preview generated successfully!'},
    'settings_pautan_pdf_tiada': {'ms': 'Pautan PDF tidak ditemui', 'en': 'PDF link not found'},
    'settings_gagal_preview': {'ms': 'Gagal menjana preview', 'en': 'Failed to generate preview'},
    'settings_gagal_muat_pdf': {'ms': 'Gagal memuat turun PDF', 'en': 'Failed to download PDF'},
    'settings_logo_melebihi': {'ms': 'Logo melebihi 200KB', 'en': 'Logo exceeds 200KB'},
    'settings_logo_berjaya': {'ms': 'Logo berjaya dimuat naik', 'en': 'Logo uploaded successfully'},
    'settings_sila_isi_tel_admin': {'ms': 'Sila isi No Telefon Admin', 'en': 'Please fill in Admin Phone No'},
    'settings_pass_min_4': {'ms': 'Password minimum 4 aksara', 'en': 'Password minimum 4 characters'},
    'settings_tel_digunakan': {'ms': 'No telefon ini sudah digunakan oleh cawangan lain', 'en': 'This phone number is already used by another branch'},
    'settings_admin_disimpan': {'ms': 'Admin disimpan & dikunci', 'en': 'Admin saved & locked'},
    'settings_kemaskini_admin': {'ms': 'Kemaskini Admin', 'en': 'Update Admin'},
    'settings_sila_kemaskini': {'ms': 'Sila kemaskini No Telefon / Password', 'en': 'Please update Phone No / Password'},
    'settings_kata_laluan_salah': {'ms': 'Kata laluan salah', 'en': 'Wrong password'},
    'settings_emel_akaun_hint': {'ms': 'Emel akaun...', 'en': 'Account email...'},
    'settings_tiada_emel': {'ms': 'Tiada emel didaftarkan', 'en': 'No email registered'},
    'settings_berjaya_reset': {'ms': 'Berjaya. Sila masukkan maklumat admin baru.', 'en': 'Success. Please enter new admin details.'},
    'settings_emel_tak_sepadan': {'ms': 'Emel tidak sepadan', 'en': 'Email does not match'},
    'settings_nota_invoice_label': {'ms': 'Nota Invoice', 'en': 'Invoice Note'},
    'settings_nota_quotation_label': {'ms': 'Nota Quotation', 'en': 'Quotation Note'},
    'settings_nota_claim_label': {'ms': 'Nota Claim Warranty', 'en': 'Warranty Claim Note'},
    'settings_nota_booking_label': {'ms': 'Nota Booking', 'en': 'Booking Note'},
    'settings_tpl_standard': {'ms': 'Standard', 'en': 'Standard'},
    'settings_tpl_moden': {'ms': 'Moden', 'en': 'Modern'},
    'settings_tpl_klasik': {'ms': 'Klasik', 'en': 'Classic'},
    'settings_tpl_minimalis': {'ms': 'Minimalis', 'en': 'Minimalist'},
    'settings_tpl_komersial': {'ms': 'Komersial', 'en': 'Commercial'},
    'settings_tpl_elegan': {'ms': 'Elegan', 'en': 'Elegant'},
    'settings_tpl_tengah': {'ms': 'Tengah', 'en': 'Center'},
    'settings_tpl_kompak': {'ms': 'Kompak', 'en': 'Compact'},
    'settings_tpl_korporat': {'ms': 'Korporat', 'en': 'Corporate'},
    'settings_tpl_kreatif': {'ms': 'Kreatif', 'en': 'Creative'},
    'settings_preview_template': {'ms': 'PREVIEW TEMPLATE', 'en': 'PREVIEW TEMPLATE'},
    'settings_printer_resit_80mm': {'ms': 'PRINTER RESIT 80MM', 'en': '80MM RECEIPT PRINTER'},
    'settings_printer_label_sticker': {'ms': 'PRINTER LABEL (Sticker)', 'en': 'LABEL PRINTER (Sticker)'},
    'settings_printer_biasa_a4': {'ms': 'PRINTER BIASA (A4)', 'en': 'NORMAL PRINTER (A4)'},
    'settings_sedang_scan': {'ms': 'SEDANG SCAN...', 'en': 'SCANNING...'},
    'settings_taip_nama_printer': {'ms': 'Taip nama printer...', 'en': 'Type printer name...'},
    'settings_printer_disimpan': {'ms': 'Printer disimpan', 'en': 'Printer saved'},
    'settings_printer_dibuang': {'ms': 'Printer dibuang', 'en': 'Printer removed'},
    'settings_sila_hidupkan_bt': {'ms': 'Sila hidupkan Bluetooth', 'en': 'Please turn on Bluetooth'},
    'settings_gagal_scan': {'ms': 'Gagal scan', 'en': 'Scan failed'},
    'settings_tiada_printer_rangkaian': {'ms': 'Tiada printer dijumpai dalam rangkaian', 'en': 'No printers found in network'},
    'settings_sedang_scan_rangkaian': {'ms': 'SEDANG SCAN RANGKAIAN...', 'en': 'SCANNING NETWORK...'},
    'settings_scan_auto_wifi': {'ms': 'SCAN AUTO — CARI PRINTER WiFi', 'en': 'AUTO SCAN — FIND WiFi PRINTER'},
    'settings_printer_dijumpai': {'ms': 'PRINTER DIJUMPAI', 'en': 'PRINTERS FOUND'},
    'settings_printer_wifi_disimpan': {'ms': 'Printer WiFi disimpan', 'en': 'WiFi printer saved'},
    'settings_printer_wifi_dibuang': {'ms': 'Printer WiFi dibuang', 'en': 'WiFi printer removed'},
    'settings_nama_printer': {'ms': 'Nama Printer', 'en': 'Printer Name'},
    'settings_cth_printer': {'ms': 'Cth: HP LaserJet', 'en': 'E.g.: HP LaserJet'},
    'settings_cth_ip': {'ms': 'Cth: 192.168.1.100', 'en': 'E.g.: 192.168.1.100'},
    'settings_sila_masuk_ip': {'ms': 'Sila masukkan IP', 'en': 'Please enter IP'},
    'settings_masukkan_password': {'ms': 'Masukkan password...', 'en': 'Enter password...'},
    'settings_warna_ditukar': {'ms': 'Warna header ditukar ke', 'en': 'Header color changed to'},
    'settings_ralat': {'ms': 'Ralat', 'en': 'Error'},
    'settings_aktif': {'ms': 'AKTIF', 'en': 'ACTIVE'},

    // ═══════════════════════════════════════
    // CREATE JOB SCREEN
    // ═══════════════════════════════════════
    'cj_buka_tiket': {'ms': 'BUKA TIKET BARU', 'en': 'OPEN NEW TICKET'},
    'cj_new_cust': {'ms': 'NEW CUST', 'en': 'NEW CUST'},
    'cj_scan': {'ms': 'SCAN', 'en': 'SCAN'},
    'cj_scan_stok': {'ms': 'SCAN STOK', 'en': 'SCAN STOCK'},
    'cj_semak': {'ms': 'SEMAK', 'en': 'CHECK'},
    'cj_tambah': {'ms': '+ TAMBAH', 'en': '+ ADD'},
    'cj_lukis_pattern': {'ms': 'LUKIS PATTERN', 'en': 'DRAW PATTERN'},
    'cj_tekan_titik': {'ms': 'Tekan titik mengikut urutan pattern.', 'en': 'Tap dots in pattern order.'},
    'cj_reset': {'ms': 'RESET', 'en': 'RESET'},
    'cj_ambil_gambar': {'ms': 'AMBIL GAMBAR KEROSAKAN', 'en': 'TAKE DAMAGE PHOTO'},
    'cj_ringkasan_bayaran': {'ms': 'RINGKASAN BAYARAN', 'en': 'PAYMENT SUMMARY'},
    'cj_baki_akhir': {'ms': 'BAKI AKHIR', 'en': 'FINAL BALANCE'},
    'cj_quote_80mm': {'ms': 'QUOTE 80mm', 'en': 'QUOTE 80mm'},
    'cj_quote_a4': {'ms': 'QUOTE A4', 'en': 'QUOTE A4'},
    'cj_tiket_berjaya': {'ms': 'Tiket berjaya disimpan', 'en': 'Ticket saved successfully'},
    'cj_voucher_dijana': {'ms': 'Voucher dijana', 'en': 'Voucher generated'},
    'cj_taip_cari_stok': {'ms': 'Taip untuk cari dari stok...', 'en': 'Type to search from stock...'},
    // Wizard steps
    'cj_step_cust': {'ms': 'PELANGGAN', 'en': 'CUSTOMER'},
    'cj_step_kerosakan': {'ms': 'KEROSAKAN & HARGA', 'en': 'DAMAGE & PRICE'},
    'cj_step_kewangan': {'ms': 'KEWANGAN', 'en': 'FINANCE'},
    'cj_step_gambar': {'ms': 'GAMBAR', 'en': 'PHOTO'},
    'cj_previous': {'ms': 'SEBELUM', 'en': 'PREVIOUS'},
    'cj_next': {'ms': 'SETERUSNYA', 'en': 'NEXT'},
    'cj_langkah': {'ms': 'Langkah', 'en': 'Step'},
    'cj_dari': {'ms': 'dari', 'en': 'of'},
    // Form labels (previously hardcoded Malay)
    'cj_nama_pelanggan': {'ms': 'NAMA PELANGGAN', 'en': 'CUSTOMER NAME'},
    'cj_masuk_nama': {'ms': 'Masukkan nama penuh...', 'en': 'Enter full name...'},
    'cj_no_telefon': {'ms': 'NO TELEFON', 'en': 'PHONE NUMBER'},
    'cj_backup': {'ms': 'BACKUP', 'en': 'BACKUP'},
    'cj_no_backup': {'ms': 'NO BACKUP', 'en': 'BACKUP NUMBER'},
    'cj_no_tel_backup_hint': {'ms': 'No telefon backup...', 'en': 'Backup phone number...'},
    'cj_model_peranti': {'ms': 'MODEL PERANTI', 'en': 'DEVICE MODEL'},
    'cj_model_hint': {'ms': 'Cth: iPhone 15 Pro Max', 'en': 'E.g. iPhone 15 Pro Max'},
    'cj_senarai_kerosakan': {'ms': 'SENARAI KEROSAKAN / ITEM', 'en': 'DAMAGE / ITEM LIST'},
    'cj_stok_digunakan': {'ms': 'STOK DIGUNAKAN', 'en': 'STOCK USED'},
    'cj_staff_menerima': {'ms': 'STAFF MENERIMA', 'en': 'RECEIVING STAFF'},
    'cj_password_pattern': {'ms': 'PASSWORD / PATTERN / VOUCHER', 'en': 'PASSWORD / PATTERN / VOUCHER'},
    'cj_pass_hint': {'ms': 'Pass / PIN / Tiada', 'en': 'Pass / PIN / None'},
    'cj_jenis_servis': {'ms': 'JENIS SERVIS', 'en': 'SERVICE TYPE'},
    'cj_nota': {'ms': 'NOTA', 'en': 'NOTE'},
    'cj_nota_tambahan_hint': {'ms': 'Nota tambahan...', 'en': 'Additional note...'},
    'cj_catatan': {'ms': 'CATATAN', 'en': 'NOTES'},
    'cj_gambar_kerosakan': {'ms': 'GAMBAR KEROSAKAN', 'en': 'DAMAGE PHOTO'},
    'cj_gambar_diambil': {'ms': 'GAMBAR DIAMBIL', 'en': 'PHOTO TAKEN'},
    'cj_tekan_snap': {'ms': 'TEKAN UNTUK SNAP GAMBAR', 'en': 'TAP TO SNAP PHOTO'},
    'cj_depan': {'ms': 'Depan', 'en': 'Front'},
    'cj_belakang': {'ms': 'Belakang', 'en': 'Back'},
    'cj_cari_pelanggan': {'ms': 'CARI PELANGGAN SEDIA ADA', 'en': 'SEARCH EXISTING CUSTOMER'},
    'cj_harga_rm': {'ms': 'HARGA (RM)', 'en': 'PRICE (RM)'},
    'cj_diskaun_rm': {'ms': 'DISKAUN (RM)', 'en': 'DISCOUNT (RM)'},
    'cj_kod_voucher': {'ms': 'KOD VOUCHER', 'en': 'VOUCHER CODE'},
    'cj_kod_voucher_ref': {'ms': 'KOD VOUCHER / REFERRAL', 'en': 'VOUCHER / REFERRAL CODE'},
    'cj_voucher_hint': {'ms': 'Cth: V-ABC123 / REF-XXXX', 'en': 'E.g. V-ABC123 / REF-XXXX'},
    'cj_deposit_rm': {'ms': 'DEPOSIT (RM)', 'en': 'DEPOSIT (RM)'},
    'cj_status_bayaran': {'ms': 'STATUS BAYARAN', 'en': 'PAYMENT STATUS'},
    'cj_cara_bayaran': {'ms': 'CARA BAYARAN', 'en': 'PAYMENT METHOD'},
    'cj_baki': {'ms': 'Baki:', 'en': 'Balance:'},
    'cj_buang': {'ms': 'BUANG', 'en': 'REMOVE'},
    'cj_cari_inventori_hint': {'ms': 'Cari inventori / taip manual...', 'en': 'Search inventory / type manually...'},

    // ═══════════════════════════════════════
    // SENARAI JOB SCREEN
    // ═══════════════════════════════════════
    'sj_senarai_job': {'ms': 'SENARAI JOB', 'en': 'JOB LIST'},
    'sj_history': {'ms': 'HISTORY', 'en': 'HISTORY'},
    'sj_csv': {'ms': 'CSV', 'en': 'CSV'},
    'sj_item_kerosakan': {'ms': 'ITEM / KEROSAKAN', 'en': 'ITEM / DAMAGE'},
    'sj_kewangan': {'ms': 'KEWANGAN', 'en': 'FINANCE'},
    'sj_staf_terima': {'ms': 'STAF TERIMA', 'en': 'RECEIVING STAFF'},
    'sj_sejarah_pelanggan': {'ms': 'SEJARAH PELANGGAN', 'en': 'CUSTOMER HISTORY'},
    'sj_gambar_selepas': {'ms': 'GAMBAR SELEPAS REPAIR', 'en': 'PHOTO AFTER REPAIR'},
    'sj_status_history': {'ms': 'STATUS HISTORY', 'en': 'STATUS HISTORY'},
    'sj_tiada_rekod': {'ms': 'Tiada rekod dijumpai', 'en': 'No records found'},
    'sj_tiada_status': {'ms': 'Tiada rekod perubahan status.', 'en': 'No status change records.'},
    'sj_tukar_status': {'ms': 'Tukar ke', 'en': 'Change to'},
    'sj_ya_tukar': {'ms': 'YA, TUKAR', 'en': 'YES, CHANGE'},
    'sj_sila_masuk_sebab': {'ms': 'Sila masukkan sebab', 'en': 'Please enter reason'},
    'sj_sila_pilih_staff': {'ms': 'Sila pilih staff', 'en': 'Please select staff'},
    'sj_pilih_staff': {'ms': 'Pilih Staff', 'en': 'Select Staff'},
    'sj_telefon': {'ms': 'Telefon', 'en': 'Phone'},
    'sj_cari_hint': {'ms': 'Cari nama, siri, item, staff, tel...', 'en': 'Search name, serial, item, staff, tel...'},
    'sj_menjana_pdf': {'ms': 'Menjana', 'en': 'Generating'},

    // ═══════════════════════════════════════
    // DASHBOARD WIDGET SCREEN
    // ═══════════════════════════════════════
    'dw_pilih_staff': {'ms': '- PILIH STAFF -', 'en': '- SELECT STAFF -'},
    'dw_sedia': {'ms': 'Sedia', 'en': 'Ready'},

    // ═══════════════════════════════════════
    // BOOKING SCREEN
    // ═══════════════════════════════════════
    'bk_daftar_booking': {'ms': 'DAFTAR BOOKING', 'en': 'REGISTER BOOKING'},
    'bk_new_booking': {'ms': 'NEW BOOKING', 'en': 'NEW BOOKING'},
    'bk_simpan_rekod': {'ms': 'SIMPAN REKOD', 'en': 'SAVE RECORD'},
    'bk_kurier': {'ms': 'KURIER', 'en': 'COURIER'},
    'bk_pengurusan_tracking': {'ms': 'PENGURUSAN TRACKING', 'en': 'TRACKING MANAGEMENT'},
    'bk_kemaskini_tracking': {'ms': 'KEMASKINI TRACKING', 'en': 'UPDATE TRACKING'},
    'bk_tracking_dikemaskini': {'ms': 'Tracking dikemaskini!', 'en': 'Tracking updated!'},
    'bk_tiada_rekod': {'ms': 'Tiada rekod booking', 'en': 'No booking records'},
    'bk_booking_berjaya': {'ms': 'berjaya!', 'en': 'success!'},
    'bk_sila_isi': {'ms': 'Sila isi Nama, Telefon dan Item!', 'en': 'Please fill in Name, Phone and Item!'},
    'bk_paid': {'ms': 'PAID', 'en': 'PAID'},
    'bk_lama': {'ms': 'Lama', 'en': 'Old'},
    'bk_az': {'ms': 'A-Z', 'en': 'A-Z'},
    'bk_za': {'ms': 'Z-A', 'en': 'Z-A'},
    'bk_delete': {'ms': 'DELETE', 'en': 'DELETE'},

    // ═══════════════════════════════════════
    // CLAIM WARRANTY SCREEN
    // ═══════════════════════════════════════
    'cw_claim_warranty': {'ms': 'CLAIM WARRANTY', 'en': 'WARRANTY CLAIM'},
    'cw_cari_repair': {'ms': 'CARI REPAIR UNTUK CLAIM', 'en': 'SEARCH REPAIR FOR CLAIM'},
    'cw_cari_desc': {'ms': 'Cari berdasarkan no siri atau no telefon pelanggan', 'en': 'Search by serial number or customer phone number'},
    'cw_cari_repair_daftar': {'ms': 'Cari repair record untuk daftar claim', 'en': 'Search repair record to register claim'},
    'cw_daftar': {'ms': 'DAFTAR', 'en': 'REGISTER'},
    'cw_daftar_claim': {'ms': 'DAFTAR CLAIM', 'en': 'REGISTER CLAIM'},
    'cw_sudah_didaftarkan': {'ms': 'SUDAH DIDAFTARKAN', 'en': 'ALREADY REGISTERED'},
    'cw_padam_claim': {'ms': 'PADAM CLAIM', 'en': 'DELETE CLAIM'},
    'cw_pdf_sedia': {'ms': 'PDF SEDIA', 'en': 'PDF READY'},
    'cw_menjana_pdf_claim': {'ms': 'Menjana PDF Claim...', 'en': 'Generating Claim PDF...'},
    'cw_tiada_claim': {'ms': 'Tiada claim warranty', 'en': 'No warranty claims'},
    'cw_tiada_claim_ditemui': {'ms': 'Tiada claim ditemui', 'en': 'No claims found'},
    'cw_tekan_daftar': {'ms': 'Tekan + DAFTAR untuk mendaftarkan claim baru', 'en': 'Press + REGISTER to register a new claim'},
    'cw_pasti_padam': {'ms': 'Adakah anda pasti mahu padam claim', 'en': 'Are you sure you want to delete claim'},
    'cw_tidak_boleh_batal': {'ms': 'Tindakan ini tidak boleh dibatalkan.', 'en': 'This action cannot be undone.'},
    'cw_hubungi': {'ms': 'Hubungi', 'en': 'Contact'},
    'cw_pilih_nombor': {'ms': 'Pilih nombor untuk dihubungi:', 'en': 'Select number to contact:'},
    'cw_whatsapp': {'ms': 'WhatsApp', 'en': 'WhatsApp'},
    'cw_tulis_nota': {'ms': 'Tulis nota mengenai claim ini...', 'en': 'Write a note about this claim...'},
    'cw_cari_hint': {'ms': 'Cari siri, pelanggan, model...', 'en': 'Search serial, customer, model...'},
    'cw_masukkan_siri': {'ms': 'Masukkan siri atau no telefon...', 'en': 'Enter serial or phone number...'},

    // ═══════════════════════════════════════
    // STOCK SCREEN
    // ═══════════════════════════════════════
    'st_stock_cn': {'ms': 'STOCK & CN', 'en': 'STOCK & CN'},
    'st_sparepart': {'ms': 'SPAREPART', 'en': 'SPAREPART'},
    'st_accessories': {'ms': 'ACCESSORIES', 'en': 'ACCESSORIES'},
    'st_tambah_stok': {'ms': 'TAMBAH STOK BARU', 'en': 'ADD NEW STOCK'},
    'st_edit': {'ms': 'EDIT', 'en': 'EDIT'},
    'st_padam_item': {'ms': 'Padam Item?', 'en': 'Delete Item?'},
    'st_pasti_padam': {'ms': 'Adakah anda pasti ingin padam', 'en': 'Are you sure you want to delete'},
    'st_return_stock': {'ms': 'RETURN STOCK', 'en': 'RETURN STOCK'},
    'st_reverse_stock': {'ms': 'REVERSE STOCK (BY JOB SIRI)', 'en': 'REVERSE STOCK (BY JOB SERIAL)'},
    'st_h_return': {'ms': 'H. RETURN', 'en': 'H. RETURN'},
    'st_h_used': {'ms': 'H. USED', 'en': 'H. USED'},
    'st_history_return': {'ms': 'HISTORY RETURN', 'en': 'RETURN HISTORY'},
    'st_history_used': {'ms': 'HISTORY STOCK USED', 'en': 'STOCK USED HISTORY'},
    'st_kategori': {'ms': 'Kategori', 'en': 'Category'},
    'st_memuatkan': {'ms': 'Memuatkan inventori...', 'en': 'Loading inventory...'},
    'st_tiada_item': {'ms': 'Tiada item dijumpai', 'en': 'No items found'},
    'st_tiada_rekod_guna': {'ms': 'Tiada rekod penggunaan stok', 'en': 'No stock usage records'},
    'st_tiada_rekod_return': {'ms': 'Tiada rekod return stok', 'en': 'No stock return records'},
    'st_tambah_gambar': {'ms': 'Tambah gambar (max 100KB)', 'en': 'Add image (max 100KB)'},
    'st_cari_hint': {'ms': 'Cari kod, nama atau siri jual...', 'en': 'Search code, name or sale serial...'},
    'st_masuk': {'ms': 'Masuk', 'en': 'In'},
    'st_jual': {'ms': 'Jual', 'en': 'Sold'},

    // ═══════════════════════════════════════
    // PHONE STOCK SCREEN
    // ═══════════════════════════════════════
    'ps_stok_telefon': {'ms': 'STOK TELEFON', 'en': 'PHONE STOCK'},
    'ps_tambah': {'ms': 'TAMBAH STOK TELEFON', 'en': 'ADD PHONE STOCK'},
    'ps_edit': {'ms': 'EDIT STOK TELEFON', 'en': 'EDIT PHONE STOCK'},
    'ps_history_sampah': {'ms': 'HISTORY & SAMPAH', 'en': 'HISTORY & TRASH'},
    'ps_bulk_csv': {'ms': 'BULK UPLOAD CSV', 'en': 'BULK UPLOAD CSV'},
    'ps_sample_csv': {'ms': 'SAMPLE CSV', 'en': 'SAMPLE CSV'},
    'ps_padam_stok': {'ms': 'Padam Stok?', 'en': 'Delete Stock?'},
    'ps_padam_kekal': {'ms': 'PADAM KEKAL', 'en': 'DELETE PERMANENTLY'},
    'ps_reverse_stock': {'ms': 'REVERSE STOCK', 'en': 'REVERSE STOCK'},
    'ps_reverse_confirm': {'ms': 'Reverse Stock?', 'en': 'Reverse Stock?'},
    'ps_halakan_kamera': {'ms': 'Halakan kamera ke QR Code atau Barcode', 'en': 'Point camera at QR Code or Barcode'},
    'ps_tekan_gambar': {'ms': 'Tekan untuk tambah gambar', 'en': 'Tap to add image'},
    'ps_tiada_padanan': {'ms': 'Tiada padanan carian', 'en': 'No search matches'},
    'ps_tiada_rekod_jual': {'ms': 'Tiada rekod jualan', 'en': 'No sales records'},
    'ps_tiada_stok': {'ms': 'Tiada stok telefon', 'en': 'No phone stock'},
    'ps_tong_kosong': {'ms': 'Tong sampah kosong', 'en': 'Trash is empty'},
    'ps_auto_padam': {'ms': 'Auto padam kekal selepas 30 hari', 'en': 'Auto permanent delete after 30 days'},
    'ps_cari_hint': {'ms': 'Cari nama, kod atau IMEI...', 'en': 'Search name, code or IMEI...'},

    // ═══════════════════════════════════════
    // KEWANGAN SCREEN
    // ═══════════════════════════════════════
    'kw_jana_laporan': {'ms': 'JANA LAPORAN PDF', 'en': 'GENERATE PDF REPORT'},
    'kw_cetak_80mm': {'ms': 'CETAK RINGKASAN 80MM', 'en': 'PRINT 80MM SUMMARY'},
    'kw_muat_turun_excel': {'ms': 'MUAT TURUN EXCEL / CSV', 'en': 'DOWNLOAD EXCEL / CSV'},
    'kw_title': {'ms': 'KEWANGAN', 'en': 'FINANCE'},
    'kw_duit_keluar': {'ms': 'DUIT KELUAR', 'en': 'EXPENSE'},
    'kw_repair_aksesori': {'ms': 'REPAIR & AKSESORI', 'en': 'REPAIR & ACCESSORIES'},
    'kw_jualan_telefon': {'ms': 'JUALAN TELEFON', 'en': 'PHONE SALES'},
    'kw_cari_hint': {'ms': 'Cari nama, siri, item, staff, tel...', 'en': 'Search name, serial, item, staff, tel...'},
    'kw_masa': {'ms': 'Masa', 'en': 'Time'},
    'kw_semua': {'ms': 'Semua', 'en': 'All'},
    'kw_hari_ini': {'ms': 'Hari Ini', 'en': 'Today'},
    'kw_minggu_ini': {'ms': 'Minggu Ini', 'en': 'This Week'},
    'kw_bulan_ini': {'ms': 'Bulan Ini', 'en': 'This Month'},
    'kw_tahun_ini': {'ms': 'Tahun Ini', 'en': 'This Year'},
    'kw_pilih_tarikh': {'ms': 'Pilih Tarikh', 'en': 'Select Date'},
    'kw_susun': {'ms': 'Susun', 'en': 'Sort'},
    'kw_terbaru': {'ms': 'Terbaru', 'en': 'Latest'},
    'kw_terdahulu': {'ms': 'Terdahulu', 'en': 'Earliest'},
    'kw_jualan_sahaja': {'ms': 'Jualan Sahaja', 'en': 'Sales Only'},
    'kw_duit_keluar_filter': {'ms': 'Duit Keluar', 'en': 'Expenses'},
    'kw_baris': {'ms': 'Baris', 'en': 'Rows'},
    'kw_memuatkan': {'ms': 'Memuatkan data kewangan...', 'en': 'Loading finance data...'},
    'kw_tiada_rekod': {'ms': 'Tiada rekod dijumpai', 'en': 'No records found'},
    'kw_cetak': {'ms': 'CETAK', 'en': 'PRINT'},
    'kw_tiada_jualan_telefon': {'ms': 'Tiada rekod jualan telefon', 'en': 'No phone sales records'},
    'kw_jual': {'ms': 'Jual', 'en': 'Sales'},
    'kw_keluar': {'ms': 'Keluar', 'en': 'Out'},
    'kw_jual_p': {'ms': 'Jual(P)', 'en': 'Sales(V)'},
    'kw_klr_p': {'ms': 'Klr(P)', 'en': 'Out(V)'},
    'kw_rekod': {'ms': 'rekod', 'en': 'records'},
    'kw_rekod_duit_keluar': {'ms': 'REKOD DUIT KELUAR', 'en': 'EXPENSE RECORD'},
    'kw_perkara': {'ms': 'Perkara / Tujuan', 'en': 'Purpose / Reason'},
    'kw_cth_spare': {'ms': 'Cth: Beli spare part', 'en': 'E.g: Buy spare part'},
    'kw_jumlah_rm': {'ms': 'Jumlah (RM)', 'en': 'Amount (RM)'},
    'kw_staff': {'ms': 'Staff', 'en': 'Staff'},
    'kw_sila_isi': {'ms': 'Sila isi semua ruangan', 'en': 'Please fill in all fields'},
    'kw_berjaya_simpan': {'ms': 'Duit keluar berjaya disimpan', 'en': 'Expense saved successfully'},
    'kw_cetak_siri': {'ms': 'CETAK', 'en': 'PRINT'},
    'kw_cetak_80mm_bt': {'ms': 'CETAK 80MM (BLUETOOTH)', 'en': 'PRINT 80MM (BLUETOOTH)'},
    'kw_cetak_resit_desc': {'ms': 'Cetak resit ringkas ke printer termal', 'en': 'Print simple receipt to thermal printer'},
    'kw_jana_pdf_a4': {'ms': 'JANA PDF A4 (INVOICE)', 'en': 'GENERATE PDF A4 (INVOICE)'},
    'kw_jana_pdf_desc': {'ms': 'Jana invoice PDF dan buka untuk cetak', 'en': 'Generate invoice PDF and open to print'},
    'kw_sambung_printer': {'ms': 'Menyambung ke printer...', 'en': 'Connecting to printer...'},
    'kw_resit_jualan': {'ms': '*** RESIT JUALAN ***', 'en': '*** SALES RECEIPT ***'},
    'kw_no_rujukan': {'ms': 'No. Rujukan', 'en': 'Ref No.'},
    'kw_jenis': {'ms': 'Jenis', 'en': 'Type'},
    'kw_tarikh': {'ms': 'Tarikh', 'en': 'Date'},
    'kw_masa_print': {'ms': 'Masa', 'en': 'Time'},
    'kw_staf': {'ms': 'Staf', 'en': 'Staff'},
    'kw_pelanggan': {'ms': 'PELANGGAN', 'en': 'CUSTOMER'},
    'kw_nama': {'ms': 'Nama', 'en': 'Name'},
    'kw_no_tel': {'ms': 'No. Tel', 'en': 'Phone No.'},
    'kw_butiran': {'ms': 'BUTIRAN', 'en': 'DETAILS'},
    'kw_item': {'ms': 'Item', 'en': 'Item'},
    'kw_cara_bayar': {'ms': 'Cara Bayar', 'en': 'Payment'},
    'kw_jumlah': {'ms': 'JUMLAH', 'en': 'TOTAL'},
    'kw_terima_kasih': {'ms': 'Terima Kasih / Thank You!', 'en': 'Thank You!'},
    'kw_berjaya_cetak': {'ms': 'Berjaya dicetak!', 'en': 'Printed successfully!'},
    'kw_gagal_cetak': {'ms': 'Gagal cetak. Pastikan printer disambung.', 'en': 'Print failed. Make sure printer is connected.'},
    'kw_menjana_pdf': {'ms': 'Menjana PDF...', 'en': 'Generating PDF...'},
    'kw_pdf_berjaya': {'ms': 'PDF berjaya dijana!', 'en': 'PDF generated successfully!'},
    'kw_pdf_tiada': {'ms': 'Pautan PDF tidak ditemui', 'en': 'PDF link not found'},
    'kw_gagal_pdf': {'ms': 'Gagal menjana PDF', 'en': 'Failed to generate PDF'},
    'kw_gagal_muat_turun': {'ms': 'Gagal muat turun PDF', 'en': 'Failed to download PDF'},
    'kw_link_disalin': {'ms': 'Link PDF disalin!', 'en': 'PDF link copied!'},
    'kw_kata_laluan_admin': {'ms': 'KATA LALUAN ADMIN', 'en': 'ADMIN PASSWORD'},
    'kw_masuk_kata_laluan': {'ms': 'Masukkan kata laluan supervisor untuk akses laporan prestasi.', 'en': 'Enter supervisor password to access performance report.'},
    'kw_kata_laluan_hint': {'ms': 'Kata laluan...', 'en': 'Password...'},
    'kw_kata_laluan_salah': {'ms': 'Kata laluan salah!', 'en': 'Wrong password!'},
    'kw_sahkan': {'ms': 'SAHKAN', 'en': 'CONFIRM'},
    'kw_laporan_prestasi': {'ms': 'LAPORAN PRESTASI', 'en': 'PERFORMANCE REPORT'},
    'kw_kategori': {'ms': 'Kategori', 'en': 'Category'},
    'kw_sales_repair': {'ms': 'Sales Repair', 'en': 'Sales Repair'},
    'kw_quick_sales': {'ms': 'Quick Sales', 'en': 'Quick Sales'},
    'kw_pro_online': {'ms': 'Pro Online', 'en': 'Pro Online'},
    'kw_pro_offline': {'ms': 'Pro Offline', 'en': 'Pro Offline'},
    'kw_jualan': {'ms': 'JUALAN', 'en': 'SALES'},
    'kw_perbelanjaan': {'ms': 'PERBELANJAAN', 'en': 'EXPENSES'},
    'kw_transaksi': {'ms': 'transaksi', 'en': 'transactions'},
    'kw_margin_bersih': {'ms': 'MARGIN BERSIH', 'en': 'NET MARGIN'},
    'kw_untung': {'ms': 'Untung', 'en': 'Profit'},
    'kw_rugi': {'ms': 'Rugi', 'en': 'Loss'},
    'kw_pecahan_staf': {'ms': 'PECAHAN MENGIKUT STAF', 'en': 'BREAKDOWN BY STAFF'},
    'kw_tiada_data_csv': {'ms': 'Tiada data untuk dimuat turun', 'en': 'No data to download'},
    'kw_csv_dimuat': {'ms': 'CSV dimuat turun', 'en': 'CSV downloaded'},
    'kw_csv_disimpan': {'ms': 'CSV disimpan', 'en': 'CSV saved'},
    'kw_gagal_csv': {'ms': 'Gagal simpan CSV', 'en': 'Failed to save CSV'},
    'kw_laporan_kewangan': {'ms': 'LAPORAN KEWANGAN', 'en': 'FINANCE REPORT'},
    'kw_tempoh': {'ms': 'Tempoh', 'en': 'Period'},
    'kw_tarikh_cetak': {'ms': 'Tarikh Cetak', 'en': 'Print Date'},
    'kw_ringkasan_jualan': {'ms': 'RINGKASAN JUALAN', 'en': 'SALES SUMMARY'},
    'kw_jumlah_jualan': {'ms': 'Jumlah Jualan', 'en': 'Total Sales'},
    'kw_bil_transaksi': {'ms': 'Bil. Transaksi', 'en': 'No. of Transactions'},
    'kw_jumlah_keluar': {'ms': 'Jumlah Keluar', 'en': 'Total Expenses'},
    'kw_pecahan_staf_print': {'ms': 'PECAHAN STAF', 'en': 'STAFF BREAKDOWN'},
    'kw_laporan_cetak_ok': {'ms': 'Laporan berjaya dicetak!', 'en': 'Report printed successfully!'},
    'kw_menjana_laporan': {'ms': 'Menjana Laporan PDF...', 'en': 'Generating PDF Report...'},
    'kw_laporan_pdf_ok': {'ms': 'Laporan PDF berjaya dijana!', 'en': 'PDF Report generated successfully!'},
    'kw_gagal_laporan': {'ms': 'Gagal menjana laporan', 'en': 'Failed to generate report'},
    'kw_nota_invoice': {'ms': 'Sila simpan dokumen ini untuk rujukan rasmi.', 'en': 'Please keep this document for official reference.'},
    'kw_unit': {'ms': 'unit', 'en': 'units'},
    'kw_arkib': {'ms': 'ARKIB', 'en': 'ARCHIVE'},
    'kw_arkib_confirm': {'ms': 'Arkibkan rekod duit keluar ini?', 'en': 'Archive this expense record?'},
    'kw_arkib_ok': {'ms': 'Rekod berjaya diarkibkan', 'en': 'Record archived successfully'},
    'kw_arkib_gagal': {'ms': 'Gagal mengarkib rekod', 'en': 'Failed to archive record'},

    // ═══════════════════════════════════════
    // DB CUST SCREEN
    // ═══════════════════════════════════════
    'dc_db_pelanggan': {'ms': 'DB PELANGGAN', 'en': 'CUSTOMER DB'},
    'dc_excel': {'ms': 'EXCEL', 'en': 'EXCEL'},
    'dc_galeri': {'ms': 'GALERI', 'en': 'GALLERY'},
    'dc_tiada_gambar': {'ms': 'TIADA GAMBAR', 'en': 'NO IMAGES'},
    'dc_pusat_tindakan': {'ms': 'PUSAT TINDAKAN', 'en': 'ACTION CENTER'},
    'dc_pelanggan': {'ms': 'Pelanggan', 'en': 'Customer'},
    'dc_generate_referral': {'ms': 'GENERATE REFERRAL', 'en': 'GENERATE REFERRAL'},
    'dc_generate_voucher': {'ms': 'GENERATE VOUCHER', 'en': 'GENERATE VOUCHER'},
    'dc_jana_referral': {'ms': 'JANA REFERRAL', 'en': 'GENERATE REFERRAL'},
    'dc_jana_voucher': {'ms': 'JANA VOUCHER', 'en': 'GENERATE VOUCHER'},
    'dc_hantar_link': {'ms': 'HANTAR LINK', 'en': 'SEND LINK'},
    'dc_referral_sedia': {'ms': 'REFERRAL SEDIA ADA:', 'en': 'EXISTING REFERRAL:'},
    'dc_voucher_sedia': {'ms': 'VOUCHER SEDIA ADA:', 'en': 'EXISTING VOUCHER:'},
    'dc_referral_claims': {'ms': 'REFERRAL CLAIMS', 'en': 'REFERRAL CLAIMS'},
    'dc_tiada_claim': {'ms': 'Tiada claim lagi', 'en': 'No claims yet'},
    'dc_tiada_referral': {'ms': 'Tiada referral dijana lagi. Jana referral dahulu.', 'en': 'No referral generated yet. Generate referral first.'},
    'dc_tiada_voucher': {'ms': 'Tiada voucher dijana lagi. Jana voucher dahulu.', 'en': 'No voucher generated yet. Generate voucher first.'},
    'dc_tiada_rekod': {'ms': 'Tiada rekod pelanggan', 'en': 'No customer records'},
    'dc_salin_link': {'ms': 'Salin Link', 'en': 'Copy Link'},
    'dc_cari_hint': {'ms': 'Cari Nama, Telefon, Model...', 'en': 'Search Name, Phone, Model...'},

    // ═══════════════════════════════════════
    // CHAT SCREEN
    // ═══════════════════════════════════════
    'ch_cari_rakan': {'ms': 'Cari Rakan Sembang', 'en': 'Search Chat Partner'},
    'ch_kongsi': {'ms': 'KONGSI', 'en': 'SHARE'},
    'ch_mulakan': {'ms': 'Mulakan perbualan', 'en': 'Start a conversation'},
    'ch_paparan': {'ms': 'Paparan: ', 'en': 'View: '},
    'ch_tekan_plus': {'ms': 'Tekan + untuk mulakan chat baru', 'en': 'Press + to start new chat'},
    'ch_tiada_mesej': {'ms': 'Tiada mesej lagi', 'en': 'No messages yet'},
    'ch_tiada_perbualan': {'ms': 'Tiada perbualan', 'en': 'No conversations'},
    'ch_tiada_status': {'ms': 'Tiada status terkini', 'en': 'No recent status'},
    'ch_taip_mesej': {'ms': 'Taip mesej...', 'en': 'Type message...'},
    'ch_apa_fikir': {'ms': 'Apa yang anda fikirkan?', 'en': 'What are you thinking?'},

    // ═══════════════════════════════════════
    // COLLAB SCREEN
    // ═══════════════════════════════════════
    'cl_hantar_tugasan': {'ms': 'HANTAR TUGASAN', 'en': 'SEND TASK'},
    'cl_hantar_tugasan_baru': {'ms': 'HANTAR TUGASAN BARU', 'en': 'SEND NEW TASK'},
    'cl_outbox': {'ms': 'OUTBOX (KERJA DIHANTAR)', 'en': 'OUTBOX (TASKS SENT)'},
    'cl_kedai_tersimpan': {'ms': 'KEDAI TERSIMPAN', 'en': 'SAVED SHOPS'},
    'cl_senarai_kedai': {'ms': 'SENARAI KEDAI (PRO)', 'en': 'SHOP LIST (PRO)'},
    'cl_direktori_dealer': {'ms': 'DIREKTORI DEALER (PRO)', 'en': 'DEALER DIRECTORY (PRO)'},
    'cl_buang': {'ms': 'BUANG', 'en': 'REMOVE'},
    'cl_kedai_buang': {'ms': 'Kedai ini akan dibuang dari senarai tersimpan.', 'en': 'This shop will be removed from saved list.'},
    'cl_kod_dealer': {'ms': 'Kod Dealer (Sistem Penerima)', 'en': 'Dealer Code (Receiving System)'},
    'cl_lihat_status': {'ms': 'LIHAT STATUS', 'en': 'VIEW STATUS'},
    'cl_maklumat_tugasan': {'ms': 'MAKLUMAT TUGASAN', 'en': 'TASK INFO'},
    'cl_semak': {'ms': 'SEMAK', 'en': 'CHECK'},
    'cl_status_terkini': {'ms': 'STATUS TERKINI:', 'en': 'CURRENT STATUS:'},
    'cl_sila_cari_siri': {'ms': 'Sila cari no. siri tiket dahulu dan tekan ENTER', 'en': 'Please search ticket serial first and press ENTER'},
    'cl_sila_semak_kod': {'ms': 'Sila semak kod dealer dahulu dan pastikan PRO AKTIF', 'en': 'Please check dealer code first and ensure PRO is ACTIVE'},
    'cl_tiada_dealer': {'ms': 'Tiada dealer pro', 'en': 'No pro dealers'},
    'cl_tiada_rekod_hantar': {'ms': 'Tiada rekod hantaran keluar', 'en': 'No outbound records'},
    'cl_tak_boleh_hantar': {'ms': 'Tidak boleh hantar ke kedai sendiri', 'en': 'Cannot send to own shop'},
    'cl_tiket_tiada_siri': {'ms': 'Tiket tidak mempunyai no. siri', 'en': 'Ticket has no serial number'},
    'cl_tugasan_berjaya': {'ms': 'berjaya dihantar ke', 'en': 'successfully sent to'},
    'cl_tidak_dijumpai': {'ms': 'tidak dijumpai dalam senarai repair', 'en': 'not found in repair list'},
    'cl_pro_aktif': {'ms': 'PRO AKTIF', 'en': 'PRO ACTIVE'},
    'cl_tiada_pro': {'ms': 'TIADA PRO MODE — dealer perlu aktifkan Pro Mode', 'en': 'NO PRO MODE — dealer needs to activate Pro Mode'},
    'cl_kod_tiada': {'ms': 'KOD TIDAK WUJUD', 'en': 'CODE DOES NOT EXIST'},
    'cl_cari_siri_hint': {'ms': 'Cari No. Siri Tiket + ENTER', 'en': 'Search Ticket Serial + ENTER'},
    'cl_cari_kod_hint': {'ms': 'Cth: KDAI01', 'en': 'E.g.: KDAI01'},
    'cl_catatan_dealer': {'ms': 'Catatan dari Dealer', 'en': 'Notes from Dealer'},
    'cl_kurier_return': {'ms': 'Kurier Return', 'en': 'Return Courier'},
    'cl_tracking_return': {'ms': 'Tracking Return', 'en': 'Return Tracking'},
    'cl_nota_dealer': {'ms': 'Nota Dari Dealer', 'en': 'Notes From Dealer'},
    'cl_tiada_nota': {'ms': 'Tiada nota.', 'en': 'No notes.'},
    'cl_tiada': {'ms': 'Tiada', 'en': 'None'},
    'cl_kata_laluan_admin': {'ms': 'Kata Laluan Admin', 'en': 'Admin Password'},
    'cl_cth_dealer': {'ms': 'Cth: BXD0001...', 'en': 'E.g.: BXD0001...'},
    'cl_taip_id_hint': {'ms': 'Taip ID atau Nama Kedai...', 'en': 'Type ID or Shop Name...'},
    'cl_semua_status': {'ms': 'SEMUA STATUS', 'en': 'ALL STATUS'},
    'cl_arkib': {'ms': 'ARKIB', 'en': 'ARCHIVE'},
    'cl_arkib_berjaya': {'ms': 'Tugasan telah diarkibkan', 'en': 'Task has been archived'},
    'cl_pulih_berjaya': {'ms': 'Tugasan telah dipulihkan', 'en': 'Task has been restored'},
    'cl_tiada_arkib': {'ms': 'Tiada rekod arkib', 'en': 'No archived records'},
    'cl_pulihkan': {'ms': 'PULIHKAN', 'en': 'RESTORE'},
    'cl_slide_arkib': {'ms': 'Leret untuk arkib', 'en': 'Swipe to archive'},

    // ═══════════════════════════════════════
    // PROFESIONAL SCREEN
    // ═══════════════════════════════════════
    'pf_dealer_book': {'ms': 'DEALER BOOK', 'en': 'DEALER BOOK'},
    'pf_buku_dealer': {'ms': 'BUKU DEALER', 'en': 'DEALER BOOK'},
    'pf_dealer_baru': {'ms': 'DEALER BARU', 'en': 'NEW DEALER'},
    'pf_pilih_dealer': {'ms': 'PILIH DEALER', 'en': 'SELECT DEALER'},
    'pf_pilih_dari_buku': {'ms': '-- Pilih dari buku dealer --', 'en': '-- Select from dealer book --'},
    'pf_job_baru': {'ms': 'JOB BARU', 'en': 'NEW JOB'},
    'pf_info_tugasan': {'ms': 'INFO TUGASAN', 'en': 'TASK INFO'},
    'pf_kemaskini_tugasan': {'ms': 'KEMASKINI TUGASAN', 'en': 'UPDATE TASK'},
    'pf_nota_penghantar': {'ms': 'NOTA DARI PENGHANTAR', 'en': 'NOTES FROM SENDER'},
    'pf_bayaran': {'ms': 'BAYARAN', 'en': 'PAYMENT'},
    'pf_kaedah': {'ms': 'KAEDAH', 'en': 'METHOD'},
    'pf_password_device': {'ms': 'PASSWORD DEVICE', 'en': 'DEVICE PASSWORD'},
    'pf_arkib': {'ms': 'ARKIB', 'en': 'ARCHIVE'},
    'pf_job_diarkib': {'ms': 'Job diarkibkan', 'en': 'Job archived'},
    'pf_tugasan_diarkib': {'ms': 'Tugasan diarkibkan', 'en': 'Task archived'},
    'pf_normal_mode': {'ms': 'NORMAL MODE', 'en': 'NORMAL MODE'},
    'pf_tukar_normal': {'ms': 'TUKAR KE NORMAL MODE?', 'en': 'SWITCH TO NORMAL MODE?'},
    'pf_tukar_normal_desc': {'ms': 'Anda akan kembali ke modul Collaboration biasa.', 'en': 'You will return to normal Collaboration module.'},
    'pf_ya_tukar': {'ms': 'YA, TUKAR', 'en': 'YES, SWITCH'},
    'pf_sila_isi_nama': {'ms': 'Sila isi Nama Kedai & Model', 'en': 'Please fill in Shop Name & Model'},
    'pf_sila_isi_kedai': {'ms': 'Sila isi nama kedai', 'en': 'Please fill in shop name'},
    'pf_tambah_manual': {'ms': 'Tambah job manual untuk\ndealer walk-in', 'en': 'Add manual job for\nwalk-in dealer'},
    'pf_tiada_dealer': {'ms': 'Tiada dealer dalam buku', 'en': 'No dealers in book'},
    'pf_tiada_job_offline': {'ms': 'Tiada job offline / walk-in', 'en': 'No offline / walk-in jobs'},
    'pf_tiada_padanan': {'ms': 'Tiada padanan carian', 'en': 'No search matches'},
    'pf_tiada_tugasan': {'ms': 'Tiada tugasan online', 'en': 'No online tasks'},
    'pf_tugasan_collab': {'ms': 'Tugasan dari rangkaian collab akan\ndipaparkan di sini', 'en': 'Tasks from collab network will\nbe displayed here'},
    'pf_tamat': {'ms': 'Tamat', 'en': 'Expires'},
    'pf_cari_hint': {'ms': 'Cari siri, nama, tel, model...', 'en': 'Search serial, name, tel, model...'},

    // ═══════════════════════════════════════
    // FUNGSI LAIN SCREEN
    // ═══════════════════════════════════════
    'fl_notifikasi_admin': {'ms': 'NOTIFIKASI DARI ADMIN HQ', 'en': 'NOTIFICATION FROM ADMIN HQ'},
    'fl_berita': {'ms': 'BERITA', 'en': 'NEWS'},
    'fl_tiada_pengumuman': {'ms': 'Tiada pengumuman tersedia.', 'en': 'No announcements available.'},
    'fl_pautan_media': {'ms': 'PAUTAN MEDIA SOSIAL', 'en': 'SOCIAL MEDIA LINKS'},
    'fl_penjana_link': {'ms': 'PENJANA LINK IN BIO', 'en': 'LINK IN BIO GENERATOR'},
    'fl_simpan_pautan': {'ms': 'SIMPAN PAUTAN BIO', 'en': 'SAVE BIO LINKS'},
    'fl_pautan_disimpan': {'ms': 'Pautan bio disimpan!', 'en': 'Bio links saved!'},
    'fl_katalog_telefon': {'ms': 'PAPAR KATALOG TELEFON', 'en': 'SHOW PHONE CATALOG'},
    'fl_katalog_desc': {'ms': 'Pautan katalog stok telefon akan dipaparkan di Link in Bio', 'en': 'Phone stock catalog link will be shown in Link in Bio'},
    'fl_rekod_pos': {'ms': 'REKOD POS & TRACKING', 'en': 'POST & TRACKING RECORDS'},
    'fl_tiada_rekod_pos': {'ms': 'Tiada rekod pos/tracking.', 'en': 'No post/tracking records.'},
    'fl_dipos': {'ms': 'DIPOS', 'en': 'POSTED'},
    'fl_dalam_perjalanan': {'ms': 'DALAM PERJALANAN', 'en': 'IN TRANSIT'},
    'fl_item_tujuan': {'ms': 'Item / Tujuan', 'en': 'Item / Purpose'},
    'fl_kurier': {'ms': 'Kurier', 'en': 'Courier'},
    'fl_no_tracking': {'ms': 'No Tracking', 'en': 'Tracking No'},
    'fl_kemaskini_rekod': {'ms': 'KEMASKINI REKOD POS', 'en': 'UPDATE POST RECORD'},
    'fl_tambah_rekod': {'ms': 'TAMBAH REKOD POS', 'en': 'ADD POST RECORD'},
    'fl_maklumat_barang': {'ms': 'Maklumat Barang', 'en': 'Item Details'},
    'fl_pautan_penuh': {'ms': 'Pautan Penuh', 'en': 'Full Link'},
    'fl_id_sahaja': {'ms': 'ID Sahaja', 'en': 'ID Only'},
    'fl_pautan_kedai': {'ms': 'Pautan Kedai', 'en': 'Shop Link'},

    // ═══════════════════════════════════════
    // LINK SCREEN
    // ═══════════════════════════════════════
    'link_title': {'ms': 'PUSAT LINK', 'en': 'LINK CENTER'},
    'link_desc': {'ms': 'Semua link kedai anda di satu tempat. Salin, buka atau kongsi terus ke WhatsApp.', 'en': 'All your shop links in one place. Copy, open or share directly to WhatsApp.'},
    'link_borang_booking': {'ms': 'BORANG BOOKING', 'en': 'BOOKING FORM'},
    'link_borang_booking_desc': {'ms': 'Link borang booking untuk pelanggan', 'en': 'Booking form link for customers'},
    'link_borang_pelanggan': {'ms': 'BORANG PELANGGAN', 'en': 'CUSTOMER FORM'},
    'link_borang_pelanggan_desc': {'ms': 'Link borang maklumat pelanggan (repair)', 'en': 'Customer info form link (repair)'},
    'link_katalog_telefon': {'ms': 'KATALOG TELEFON', 'en': 'PHONE CATALOG'},
    'link_katalog_telefon_desc': {'ms': 'Link katalog stok telefon untuk pelanggan', 'en': 'Phone stock catalog link for customers'},
    'link_bio': {'ms': 'LINK IN BIO', 'en': 'LINK IN BIO'},
    'link_bio_desc': {'ms': 'Link profil kedai dengan semua pautan sosial', 'en': 'Shop profile link with all social links'},
    'link_salin': {'ms': 'SALIN', 'en': 'COPY'},
    'link_buka': {'ms': 'BUKA', 'en': 'OPEN'},
    'link_kongsi': {'ms': 'KONGSI', 'en': 'SHARE'},

    // ═══════════════════════════════════════
    // REFERRAL SCREEN
    // ═══════════════════════════════════════
    'rf_referral': {'ms': 'REFERRAL', 'en': 'REFERRAL'},
    'rf_cari_pelanggan': {'ms': 'CARI PELANGGAN', 'en': 'SEARCH CUSTOMER'},
    'rf_cari_desc': {'ms': 'Cari pelanggan menggunakan nombor siri atau telefon dari rekod pembaikan.', 'en': 'Search customer using serial number or phone from repair records.'},
    'rf_jana_kod': {'ms': 'JANA KOD', 'en': 'GENERATE CODE'},
    'rf_edit_referral': {'ms': 'EDIT REFERRAL', 'en': 'EDIT REFERRAL'},
    'rf_padam_referral': {'ms': 'PADAM REFERRAL?', 'en': 'DELETE REFERRAL?'},
    'rf_hantar': {'ms': 'HANTAR', 'en': 'SEND'},
    'rf_sejarah_tuntutan': {'ms': 'SEJARAH TUNTUTAN', 'en': 'CLAIM HISTORY'},
    'rf_masukkan_pin': {'ms': 'MASUKKAN PIN ADMIN', 'en': 'ENTER ADMIN PIN'},
    'rf_sudah_ada': {'ms': 'SUDAH ADA', 'en': 'ALREADY EXISTS'},
    'rf_tiada_hasil': {'ms': 'Tiada hasil carian', 'en': 'No search results'},
    'rf_tiada_padanan': {'ms': 'Tiada padanan carian', 'en': 'No search matches'},
    'rf_tiada_rekod': {'ms': 'Tiada rekod referral', 'en': 'No referral records'},
    'rf_tiada_sejarah': {'ms': 'Tiada sejarah tuntutan', 'en': 'No claim history'},
    'rf_cari_hint': {'ms': 'Cari siri atau no telefon...', 'en': 'Search serial or phone no...'},
    'rf_pin_hint': {'ms': 'Masukkan PIN staff...', 'en': 'Enter staff PIN...'},

    // ═══════════════════════════════════════
    // MAKLUM BALAS SCREEN
    // ═══════════════════════════════════════
    'mb_prestasi': {'ms': 'PRESTASI KEDAI', 'en': 'SHOP PERFORMANCE'},
    'mb_lihat_staf': {'ms': 'Lihat Staf', 'en': 'View Staff'},
    'mb_maklumat_staf': {'ms': 'MAKLUMAT STAF', 'en': 'STAFF INFO'},
    'mb_tiada_maklum': {'ms': 'Tiada maklum balas', 'en': 'No feedback'},
    'mb_terdahulu': {'ms': 'Terdahulu', 'en': 'Earlier'},
    'mb_5_bintang': {'ms': '5 Bintang', 'en': '5 Stars'},
    'mb_4_bintang': {'ms': '4 Bintang', 'en': '4 Stars'},
    'mb_3_bintang': {'ms': '3 Bintang', 'en': '3 Stars'},
    'mb_2_bintang': {'ms': '2 Bintang', 'en': '2 Stars'},
    'mb_1_bintang': {'ms': '1 Bintang', 'en': '1 Star'},
    'mb_terima': {'ms': 'Terima', 'en': 'Receive'},
    'mb_repair': {'ms': 'Repair', 'en': 'Repair'},
    'mb_serah': {'ms': 'Serah', 'en': 'Deliver'},
    'mb_cari_hint': {'ms': 'Cari Siri, Nama, Tel...', 'en': 'Search Serial, Name, Tel...'},
    'mb_menunjukkan': {'ms': 'Menunjukkan', 'en': 'Showing'},
    'mb_rekod': {'ms': 'rekod', 'en': 'records'},

    // ═══════════════════════════════════════
    // REFUND SCREEN
    // ═══════════════════════════════════════
    'rd_mohon_refund': {'ms': 'MOHON REFUND', 'en': 'REQUEST REFUND'},
    'rd_mohon_refund_hq': {'ms': 'MOHON REFUND KE HQ', 'en': 'REQUEST REFUND TO HQ'},
    'rd_hantar_permohonan': {'ms': 'HANTAR PERMOHONAN KE HQ', 'en': 'SEND REQUEST TO HQ'},
    'rd_sejarah_status': {'ms': 'SEJARAH & STATUS REFUND', 'en': 'REFUND HISTORY & STATUS'},
    'rd_maklumat_bayaran': {'ms': 'MAKLUMAT PEMBAYARAN', 'en': 'PAYMENT INFO'},
    'rd_amaun_refund': {'ms': 'Amaun Refund (RM)', 'en': 'Refund Amount (RM)'},
    'rd_sebab_refund': {'ms': 'Sebab Refund', 'en': 'Refund Reason'},
    'rd_kaedah_bayaran': {'ms': 'Kaedah Bayaran', 'en': 'Payment Method'},
    'rd_approve': {'ms': 'APPROVE', 'en': 'APPROVE'},
    'rd_pengesahan_admin': {'ms': 'Pengesahan Admin', 'en': 'Admin Verification'},
    'rd_kata_laluan_salah': {'ms': 'Kata laluan salah!', 'en': 'Wrong password!'},
    'rd_kelajuan': {'ms': 'Kelajuan', 'en': 'Speed'},
    'rd_segera': {'ms': 'SEGERA', 'en': 'URGENT'},
    'rd_tertunda': {'ms': 'TERTUNDA', 'en': 'PENDING'},
    'rd_transfer': {'ms': 'TRANSFER', 'en': 'TRANSFER'},
    'rd_cash': {'ms': 'CASH', 'en': 'CASH'},
    'rd_permohonan_dihantar': {'ms': 'Permohonan refund dihantar!', 'en': 'Refund request sent!'},
    'rd_refund_diluluskan': {'ms': 'Refund diluluskan!', 'en': 'Refund approved!'},
    'rd_isi_amaun': {'ms': 'Isi amaun & sebab', 'en': 'Fill in amount & reason'},
    'rd_cari_siri': {'ms': 'Cari No. Siri Tiket', 'en': 'Search Ticket Serial No'},
    'rd_cari_dahulu': {'ms': 'Cari siri dahulu', 'en': 'Search serial first'},
    'rd_siri_tidak_dijumpai': {'ms': 'tidak dijumpai', 'en': 'not found'},
    'rd_sila_set_password': {'ms': 'Sila set kata laluan admin di Settings', 'en': 'Please set admin password in Settings'},
    'rd_tiada_permohonan': {'ms': 'Tiada permohonan refund', 'en': 'No refund requests'},
    'rd_nota_bankin': {'ms': '* Refund bank-in mengambil masa selewat-lewatnya 7 hari bekerja.', 'en': '* Bank-in refund takes up to 7 business days.'},
    'rd_cari_hint': {'ms': 'Cari Siri / Sebab...', 'en': 'Search Serial / Reason...'},
    'rd_cth_sebab': {'ms': 'Cth: Batal order, Tiada part...', 'en': 'E.g.: Cancel order, No part...'},
    'rd_nama_bank': {'ms': 'Nama Bank', 'en': 'Bank Name'},
    'rd_cth_bank': {'ms': 'Cth: Maybank', 'en': 'E.g.: Maybank'},
    'rd_nama_pemilik': {'ms': 'Nama Pemilik Akaun', 'en': 'Account Holder Name'},
    'rd_no_akaun': {'ms': 'No Akaun', 'en': 'Account No'},
    'rd_kata_laluan_hint': {'ms': 'Kata laluan...', 'en': 'Password...'},
    'rd_masukkan_sebab_hint': {'ms': 'Masukkan sebab / reason...', 'en': 'Enter reason...'},

    // ═══════════════════════════════════════
    // JUAL TELEFON SCREEN
    // ═══════════════════════════════════════
    'jt_jual_telefon': {'ms': 'JUAL TELEFON', 'en': 'SELL PHONE'},
    'jt_addon_aksesori': {'ms': 'ADD ON (Aksesori / Case / Tempered Glass)', 'en': 'ADD ON (Accessories / Case / Tempered Glass)'},
    'jt_addon_title': {'ms': 'ADD ON — AKSESORI', 'en': 'ADD ON — ACCESSORIES'},
    'jt_generate_invoice': {'ms': 'GENERATE INVOICE', 'en': 'GENERATE INVOICE'},
    'jt_invoice_sedia': {'ms': 'INVOICE SEDIA', 'en': 'INVOICE READY'},
    'jt_menjana_invoice': {'ms': 'Menjana Invoice...', 'en': 'Generating Invoice...'},
    'jt_scan_barcode': {'ms': 'Scan barcode / IMEI telefon', 'en': 'Scan phone barcode / IMEI'},
    'jt_ditambah': {'ms': 'Ditambah', 'en': 'Added'},
    'jt_tiada_item': {'ms': 'Tiada item', 'en': 'No items'},
    'jt_tiada_rekod': {'ms': 'Tiada rekod jualan telefon', 'en': 'No phone sales records'},
    'jt_padam_rekod': {'ms': 'Padam Rekod?', 'en': 'Delete Record?'},
    'jt_padam_desc': {'ms': 'Rekod jualan ini akan dipadam.', 'en': 'This sales record will be deleted.'},
    'jt_view_pdf': {'ms': 'VIEW PDF', 'en': 'VIEW PDF'},
    'jt_wasap': {'ms': 'WASAP', 'en': 'WHATSAPP'},
    'jt_cari_hint': {'ms': 'Cari aksesori...', 'en': 'Search accessories...'},

    // ═══════════════════════════════════════
    // LOST SCREEN
    // ═══════════════════════════════════════
    'ls_rekod_kerugian': {'ms': 'REKOD KERUGIAN', 'en': 'LOSS RECORDS'},
    'ls_rekod_baru': {'ms': 'REKOD BARU', 'en': 'NEW RECORD'},
    'ls_jumlah_kerugian': {'ms': 'JUMLAH KERUGIAN', 'en': 'TOTAL LOSS'},
    'ls_jenis_kerugian': {'ms': 'Jenis Kerugian', 'en': 'Loss Type'},
    'ls_jumlah_rm': {'ms': 'Jumlah Kerugian (RM)', 'en': 'Loss Amount (RM)'},
    'ls_keterangan': {'ms': 'Keterangan / Sebab', 'en': 'Description / Reason'},
    'ls_no_siri': {'ms': 'No. Siri / Rujukan (Opsional)', 'en': 'Serial No / Reference (Optional)'},
    'ls_padam_rekod': {'ms': 'Padam Rekod?', 'en': 'Delete Record?'},
    'ls_padam_kekal': {'ms': 'Rekod ini akan dipadam secara kekal.', 'en': 'This record will be permanently deleted.'},
    'ls_rekod_dipadam': {'ms': 'Rekod dipadam', 'en': 'Record deleted'},
    'ls_isi_jumlah': {'ms': 'Isi jumlah & keterangan', 'en': 'Fill in amount & description'},
    'ls_semoga_selamat': {'ms': 'Semoga kedai sentiasa selamat!', 'en': 'May the shop always be safe!'},
    'ls_tiada_rekod': {'ms': 'Tiada rekod kerugian', 'en': 'No loss records'},
    'ls_pecah_masa': {'ms': 'Pecah Masa Pasang', 'en': 'Broken During Install'},
    'ls_cn_tak_approve': {'ms': 'CN Tak Approve', 'en': 'CN Not Approved'},
    'ls_rosak_defect': {'ms': 'Rosak/Defect', 'en': 'Damaged/Defect'},
    'ls_hilang': {'ms': 'Hilang', 'en': 'Lost'},
    'ls_lain_lain': {'ms': 'Lain-lain', 'en': 'Others'},
    'ls_cari_hint': {'ms': 'Cari keterangan / siri...', 'en': 'Search description / serial...'},
    'ls_cth_siri': {'ms': 'Cth: RMS2024...', 'en': 'E.g.: RMS2024...'},
    'ls_cth_keterangan': {'ms': 'Cth: Screen pecah masa pasang, CN tak lepas dari supplier...', 'en': 'E.g.: Screen broken during install, CN not approved by supplier...'},

    // ═══════════════════════════════════════
    // SUPERVISOR - UNTUNG RUGI TAB
    // ═══════════════════════════════════════
    'sv_ur_title': {'ms': 'LAPORAN UNTUNG RUGI', 'en': 'PROFIT & LOSS REPORT'},
    'sv_ur_today': {'ms': 'Hari Ini', 'en': 'Today'},
    'sv_ur_this_week': {'ms': 'Minggu Ini', 'en': 'This Week'},
    'sv_ur_this_month': {'ms': 'Bulan Ini', 'en': 'This Month'},
    'sv_ur_all': {'ms': 'Semua', 'en': 'All'},
    'sv_ur_pick_date': {'ms': 'Pilih Tarikh', 'en': 'Select Date'},
    'sv_ur_tab_repair': {'ms': 'REPAIR', 'en': 'REPAIR'},
    'sv_ur_tab_phone': {'ms': 'TELEFON', 'en': 'PHONE'},
    'sv_ur_tab_finance': {'ms': 'KEWANGAN', 'en': 'FINANCE'},
    'sv_ur_job_done': {'ms': 'job siap', 'en': 'jobs done'},
    'sv_ur_cost': {'ms': 'KOS', 'en': 'COST'},
    'sv_ur_profit': {'ms': 'PROFIT', 'en': 'PROFIT'},
    'sv_ur_loss': {'ms': 'RUGI', 'en': 'LOSS'},
    'sv_ur_income': {'ms': 'Pendapatan', 'en': 'Income'},
    'sv_ur_records': {'ms': 'rekod', 'en': 'records'},
    'sv_ur_expense': {'ms': 'Belanja', 'en': 'Expense'},
    'sv_ur_unit_sold': {'ms': 'unit terjual', 'en': 'units sold'},
    'sv_ur_phone_modal': {'ms': 'modal telefon', 'en': 'phone capital'},
    'sv_ur_sales': {'ms': 'Jualan', 'en': 'Sales'},
    'sv_ur_no_records': {'ms': 'Tiada rekod', 'en': 'No records'},
    // Kewangan sub-section
    'sv_ur_kw_summary': {'ms': 'Ringkasan', 'en': 'Summary'},
    'sv_ur_kw_sales': {'ms': 'JUALAN', 'en': 'SALES'},
    'sv_ur_kw_expenses': {'ms': 'PERBELANJAAN', 'en': 'EXPENSES'},
    'sv_ur_kw_gross': {'ms': 'UNTUNG KASAR', 'en': 'GROSS PROFIT'},
    'sv_ur_kw_net': {'ms': 'UNTUNG BERSIH', 'en': 'NET PROFIT'},
    'sv_ur_kw_sales_list': {'ms': 'SENARAI JUALAN', 'en': 'SALES LIST'},
    'sv_ur_kw_expense_list': {'ms': 'SENARAI PERBELANJAAN', 'en': 'EXPENSE LIST'},
    'sv_ur_kw_breakdown': {'ms': 'PECAHAN JUALAN', 'en': 'SALES BREAKDOWN'},
    'sv_ur_kw_servis': {'ms': 'Servis / Repair', 'en': 'Service / Repair'},
    'sv_ur_kw_jualan_pantas': {'ms': 'Jualan Pantas', 'en': 'Quick Sales'},
    'sv_ur_kw_phone_sales': {'ms': 'Jualan Telefon', 'en': 'Phone Sales'},
    'sv_ur_kw_total_sales': {'ms': 'Jumlah Jualan', 'en': 'Total Sales'},
    'sv_ur_kw_cogs': {'ms': 'Kos Barang (Telefon)', 'en': 'COGS (Phone)'},

    // ═══════════════════════════════════════
    // SUPERVISOR - SETTINGS
    // ═══════════════════════════════════════
    'sv_settings_title': {'ms': 'TETAPAN', 'en': 'SETTINGS'},
    'sv_settings_language': {'ms': 'BAHASA / LANGUAGE', 'en': 'LANGUAGE / BAHASA'},
    'sv_settings_language_desc': {'ms': 'Pilih bahasa paparan untuk supervisor', 'en': 'Select display language for supervisor'},
    'sv_settings_malay': {'ms': 'Bahasa Melayu', 'en': 'Bahasa Melayu'},
    'sv_settings_english': {'ms': 'English', 'en': 'English'},
    'sv_settings_saved': {'ms': 'Tetapan disimpan', 'en': 'Settings saved'},

    // SUPERVISOR - UNTUNG RUGI DOWNLOAD/REPORT
    'sv_ur_download': {'ms': 'MUAT TURUN', 'en': 'DOWNLOAD'},
    'sv_ur_report_title': {'ms': 'LAPORAN PRESTASI', 'en': 'PERFORMANCE REPORT'},
    'sv_ur_period': {'ms': 'Tempoh', 'en': 'Period'},
    'sv_ur_dl_csv': {'ms': 'MUAT TURUN EXCEL / CSV', 'en': 'DOWNLOAD EXCEL / CSV'},
    'sv_ur_dl_80mm': {'ms': 'CETAK RINGKASAN 80MM', 'en': 'PRINT 80MM SUMMARY'},
    'sv_ur_dl_pdf': {'ms': 'JANA LAPORAN PDF', 'en': 'GENERATE PDF REPORT'},
    'sv_ur_no_data': {'ms': 'Tiada data untuk dimuat turun', 'en': 'No data to download'},
    'sv_ur_connecting_printer': {'ms': 'Menyambung ke printer...', 'en': 'Connecting to printer...'},
    'sv_ur_print_date': {'ms': 'Tarikh Cetak', 'en': 'Print Date'},
    'sv_ur_total_trans': {'ms': 'Bil. Transaksi', 'en': 'Transactions'},
    'sv_ur_total_out': {'ms': 'Jumlah Keluar', 'en': 'Total Out'},
    'sv_ur_print_success': {'ms': 'Laporan berjaya dicetak!', 'en': 'Report printed successfully!'},
    'sv_ur_print_fail': {'ms': 'Gagal cetak. Pastikan printer disambung.', 'en': 'Print failed. Ensure printer is connected.'},
    'sv_ur_generating_pdf': {'ms': 'Menjana Laporan PDF...', 'en': 'Generating PDF Report...'},
    'sv_ur_pdf_success': {'ms': 'Laporan PDF berjaya dijana!', 'en': 'PDF report generated!'},
    'sv_ur_pdf_no_link': {'ms': 'Pautan PDF tidak ditemui', 'en': 'PDF link not found'},
    'sv_ur_pdf_fail': {'ms': 'Gagal menjana laporan', 'en': 'Failed to generate report'},
    'sv_ur_error': {'ms': 'Ralat', 'en': 'Error'},
  };
}
